import sqlite3
con=sqlite3.Connection('hrdb')
cur=con.cursor()
from Tkinter import *
root=Tk()
Label(root,text='Employee Record Keeping System:',font="times 20 bold italic").grid(row=0,column=1)
Label(root,text='Enter Emp Code:').grid(row=1,column=0)
e1=Entry(root)
e1.grid(row=1,column=1)
Label(root,text='Enter First Name:').grid(row=2,column=0)
e2=Entry(root)
e2.grid(row=2,column=1)
Label(root,text='Enter Last Name:').grid(row=3,column=0)
e3=Entry(root)
e3.grid(row=3,column=1)
Label(root,text='Enter Id To Fetch Record:').grid(row=4,column=0)
e4=Entry(root)
e4.grid(row=4,column=1)
def insert():
    cur.execute("create table if not exists employee(code number,fname varchar(30),lname varchar(30))")
    cur.execute("insert into employee values(e1.get(),e2.get(),e3.get())")
    con.commit()
Button(root,text="Insert",command=insert).grid(row=6,column=0)
Button(root,text="Show",command=show).grid(row=6,column=1)
Button(root,text="Show All").grid(row=6,column=2)
root.mainloop()
